# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = xrandr --output DP-3 --primary

#exec-once = ~/.config/pulse-mic-setup.sh
#exec-once = ~/.config/pipewire-setup.sh
#exec-once = qpwgraph -m -a ~/default_audio.qpwgraph
exec-once = ~/.config/onedrive-sync.sh
exec-once = keepassxc
exec-once = ~/.config/start-discord.sh
exec-once = steam
exec-once = tidal-hifi
exec-once = dimland -o HDMI-A-1
exec-once = easyeffects
exec-once = sh -c 'sleep 5; flatpak run com.core447.StreamController -b'
=======
# Input method
# exec-once = fcitx5

