# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

input {
    kb_layout = fi
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35
    sensitivity = 0
    scroll_factor = 1.5

    follow_mouse = 1
    off_window_axis_events = 2

    accel_profile = flat

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.5
    }
}

device {
  name = g-wolves-g-wolves-fenrir-asym-8k-wireless-mouse-n
  sensitivity = -0.3
  scroll_factor = 2
}

device {
  name = tenizo-tenizo_r7series_tc
  output = HDMI-A-1
  transform = 3
}

device {
  name = wacom-one-by-wacom-m-pen
  output = DP-3
}

device {
  name = weylus-stylus
  output = HEADLESS-2
}
# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
